### ISSUE TITLE
interact_sky failed with unhelpful error when TargetPixelFile has no target coordinate

### ISSUE THREAD

**Issue by orionlee** [lightkurve/lightkurve#1087]
#### Problem description
`interact_sky()` failed with a unhelpful `TypeError` when the TargetPixelFile has no target coordinate
 (`RA_OBJ` and `DEC_OBJ` header)

`interact_sky()` indeed cannot proceed without the target's coordinate, but it should raise an exception that explained the reason.

#### Example

```python
import lightkurve as lk

# tpf is obtained from somewhere
hdr = tpf.hdu[0].header
for k in ["RA_OBJ", "DEC_OBJ"]:
    del hdr[k]

tpf.interact_sky();
```

```python
ERROR:tornado.application:Uncaught exception GET /autoload.js?bokeh-autoload-element=1291&bokeh-absolute-url=http://localhost:58470&resources=none (::1)
HTTPServerRequest(protocol='http', host='localhost:58470', method='GET', uri='/autoload.js?bokeh-autoload-element=1291&bokeh-absolute-url=http://localhost:58470&resources=none', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "c:\pkg\_winnonportables\anaconda3\envs\lkv2_dev\lib\site-packages\tornado\web.py", line 1704, in _execute
    result = await result
  File "c:\pkg\_winnonportables\anaconda3\envs\lkv2_dev\lib\site-packages\bokeh\server\views\autoload_js_handler.py", line 60, in get
    session = await self.get_session()
  File "c:\pkg\_winnonportables\anaconda3\envs\lkv2_dev\lib\site-packages\bokeh\server\views\session_handler.py", line 120, in get_session
    session = await self.application_context.create_session_if_needed(session_id, self.request, token)
  File "c:\pkg\_winnonportables\anaconda3\envs\lkv2_dev\lib\site-packages\bokeh\server\contexts.py", line 218, in create_session_if_needed
    self._application.initialize_document(doc)
  File "c:\pkg\_winnonportables\anaconda3\envs\lkv2_dev\lib\site-packages\bokeh\application\application.py", line 171, in initialize_document
    h.modify_document(doc)
  File "c:\pkg\_winnonportables\anaconda3\envs\lkv2_dev\lib\site-packages\bokeh\application\handlers\function.py", line 132, in modify_document
    self._func(doc)
  File "C:\dev\lightkurve\src\lightkurve\interact.py", line 1136, in create_interact_ui
    tpf, fig_tpf, magnitude_limit=magnitude_limit
  File "C:\dev\lightkurve\src\lightkurve\interact.py", line 391, in add_gaia_figure_elements
    c1 = SkyCoord(tpf.ra, tpf.dec, frame="icrs", unit="deg")
  File "c:\pkg\_winnonportables\anaconda3\envs\lkv2_dev\lib\site-packages\astropy\coordinates\sky_coordinate.py", line 316, in __init__
    frame_cls(**frame_kwargs), args, kwargs)
  File "c:\pkg\_winnonportables\anaconda3\envs\lkv2_dev\lib\site-packages\astropy\coordinates\sky_coordinate_parsers.py", line 301, in _parse_coordinate_data
    _components[frame_attr_name] = attr_class(arg, unit=unit)
  File "c:\pkg\_winnonportables\anaconda3\envs\lkv2_dev\lib\site-packages\astropy\coordinates\angles.py", line 642, in __new__
    self = super().__new__(cls, angle, unit=unit, **kwargs)
  File "c:\pkg\_winnonportables\anaconda3\envs\lkv2_dev\lib\site-packages\astropy\coordinates\angles.py", line 137, in __new__
    return super().__new__(cls, angle, unit, dtype=dtype, copy=copy)
  File "c:\pkg\_winnonportables\anaconda3\envs\lkv2_dev\lib\site-packages\astropy\units\quantity.py", line 383, in __new__
    raise TypeError("The value must be a valid Python or "
TypeError: The value must be a valid Python or Numpy numeric type.
ERROR:tornado.access:500 GET /autoload.js?bokeh-autoload-element=1291&bokeh-absolute-url=http://localhost:58470&resources=none (::1) 12.96ms
```

#### Environment

-  platform (e.g. Linux, OSX, Windows): Windows
-  lightkurve version (e.g. 1.0b6): 2.0.10 (it should affect all older versions)
-  installation method (e.g. pip, conda, source): conda

**Comment by orionlee** [comment]
@barensten this issue can be closed with PR #1088 merged - github's auto close didn't catch it.
