### ISSUE TITLE
`MaskedQuantity` breaking `aggregate_downsample`/`bin` with Astropy 5.0

### ISSUE THREAD

**Issue by dhomeier** [lightkurve/lightkurve#1157]
#### Problem description
I've run into a test failure with the `TESS_SIM` lightkurve with astropy 5.0rc1 installed:
With 4.x, the masked columns were read in as plain `Quantity` with the masked values replaced:
#### Example
```python
import lightkurve as lk
from astropy import units as u
tess = lk.io.read('https://archive.stsci.edu/missions/tess/ete-6/tid/00/000/004/104/tess2019128220341-0000000410458113-0016-s_lc.fits')
tess.mask is None
True

tess['psf_centr2_err']
<Quantity [nan, nan, nan, ..., nan, nan, nan] pix>
```
with 5.0rc1 those columns are instead read in as `MaskedQuantity` objects:
```python
tess['psf_centr2_err']
<MaskedQuantity [———, ———, ———, ..., ———, ———, ———] pix>

tess.mask[:2]
<Table length=3>
 time  flux flux_err timecorr cadenceno centroid_col centroid_row ... psf_centr2_err mom_centr1 mom_centr1_err mom_centr2 mom_centr2_err pos_corr1 pos_corr2
 bool  bool   bool     bool      bool       bool         bool     ...      bool         bool         bool         bool         bool         bool      bool  
----- ----- -------- -------- --------- ------------ ------------ ... -------------- ---------- -------------- ---------- -------------- --------- ---------
False False    False    False     False        False        False ...           True      False          False      False          False     False     False
False False    False    False     False        False        False ...           True      False          False      False          False     False     False

tess.bin(time_bin_size=20*u.min)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/lib/python3.8/site-packages/astropy/utils/decorators.py", line 547, in wrapper
    return function(*args, **kwargs)
  File "/opt/lib/python3.8/site-packages/lightkurve/lightcurve.py", line 1458, in bin
    ts = aggregate_downsample(
  File "/opt/lib/python3.8/site-packages/astropy/timeseries/downsample.py", line 199, in aggregate_downsample
    data[unique_indices] = u.Quantity(reduceat(values.value, groups, aggregate_func),
  File "/opt/lib/python3.8/site-packages/astropy/timeseries/downsample.py", line 29, in reduceat
    result.append(function(array[indices[i]:indices[i+1]]))
  File "<__array_function__ internals>", line 5, in nanmean
TypeError: no implementation found for 'numpy.nanmean' on types that implement __array_function__: [<class 'astropy.utils.masked.core.MaskedNDArray'>]
```
The failure in `aggregate_downsample` could be bypassed by providing a custom `aggregate_func`, but `Lightcurve.bin` is also using `np.nansum`, for which a workaround would have to be found as well:
```python
tess.bin(time_bin_size=20*u.min, aggregate_func=lambda x: np.nanmean(getattr(x, 'unmasked', x)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/derek/opt/lib/python3.8/site-packages/astropy/utils/decorators.py", line 547, in wrapper
    return function(*args, **kwargs)
  File "/Users/derek/opt/lib/python3.8/site-packages/lightkurve/lightcurve.py", line 1474, in bin
    ts_err = aggregate_downsample(
  File "/Users/derek/opt/lib/python3.8/site-packages/astropy/timeseries/downsample.py", line 199, in aggregate_downsample
    data[unique_indices] = u.Quantity(reduceat(values.value, groups, aggregate_func),
  File "/Users/derek/opt/lib/python3.8/site-packages/astropy/timeseries/downsample.py", line 29, in reduceat
    result.append(function(array[indices[i]:indices[i+1]]))
  File "/Users/derek/opt/lib/python3.8/site-packages/lightkurve/lightcurve.py", line 1470, in <lambda>
    lambda x: np.sqrt(np.nansum(x ** 2)) / len(np.atleast_1d(x))
  File "<__array_function__ internals>", line 5, in nansum
TypeError: no implementation found for 'numpy.nansum' on types that implement __array_function__: [<class 'astropy.utils.masked.core.MaskedNDArray'>]
```
Note that this is unrelated to the new and improved `aggregate_downsample` in 5.0rc1, but probably introduced by the wider introduction of Masked classes in astropy/astropy#11127. The same errors can be triggered in 4.3 by explicitly passing `Masked(quantity)` data to the function.
#### Expected behavior
There are other uses of `np.nanmean` et al. on lightcurve columns that may be broken by this as well, so until astropy can provide more complete support for `MaskedQuantity`, it may be necessary to explicitly convert all data to regular `Quantity` instances in the old style. Might also be relevant for #1109.
#### Environment
Python: 3.8.12 / 3.9.8 / 3.10.0
Platform: macOS-10.14.6-x86_64-i386-64bit
Astropy: 5.0rc1
Numpy: 1.21.2
Scipy: 1.7.1
Matplotlib: 3.5.0rc1
Scikit-image: 1.0.1
Lightkurve: 2.0.12dev
-  installation method: source (git HEAD)

**Comment by dhomeier** [comment]
Fixed in astropy/astropy#12435 and astropy/astropy#12454, thanks a lot @mvhk!
