### ISSUE TITLE
How to use this module behind a authenticated proxy network?

### ISSUE THREAD

**Issue by akankshaprl** [lightkurve/lightkurve#1164]
#### Example

```python
from lightkurve import LightCurve
import lightkurve as lk
import numpy as np


search_result = lk.search_tesscut('Gaia DR25290850609994130560')
lk.log.setLevel('INFO')

search_result_s4 = lk.search_tesscut('Gaia DR25290850609994130560', sector=4)
tpfs_s4 = search_result_s4.download(cutout_size=10)
print(tpfs_s4)
```

#### Expected behavior

Should come TessTargetPixelFile(TICID: Gaia DR25290850609994130560)

#### Environment

-  platform (e.g. Linux, OSX, Windows): OSX
-  lightkurve version (e.g. 1.0b6): 2.0.6
-  installation method (e.g. pip, conda, source): conda

Output
```shell
raceback (most recent call last):

  File "/Users/paras/opt/anaconda3/lib/python3.8/site-packages/lightkurve/search.py", line 231, in _download_one
    path = self._fetch_tesscut_path(

  File "/Users/paras/opt/anaconda3/lib/python3.8/site-packages/lightkurve/search.py", line 506, in _fetch_tesscut_path
    sec = TesscutClass().get_sectors(coords)

  File "/Users/paras/opt/anaconda3/lib/python3.8/site-packages/astroquery/mast/cutouts.py", line 148, in get_sectors
    response = self._service_api_connection.service_request_async("sector", params)

  File "/Users/paras/opt/anaconda3/lib/python3.8/site-packages/astroquery/utils/class_or_instance.py", line 25, in f
    return self.fn(obj, *args, **kwds)

  File "/Users/paras/opt/anaconda3/lib/python3.8/site-packages/astroquery/mast/services.py", line 271, in service_request_async
    response = self._request('POST', request_url, data=catalogs_request, headers=headers)

  File "/Users/paras/opt/anaconda3/lib/python3.8/site-packages/astroquery/mast/services.py", line 181, in _request
    response.raise_for_status()

  File "/Users/paras/opt/anaconda3/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)

HTTPError: 502 Server Error: Bad Gateway for url: https://mast.stsci.edu/tesscut/api/v0.1/sector


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-4-e4b3c7719c06>", line 10, in <module>
    tpfs_s4 = search_result_s4.download(cutout_size=10)

  File "/Users/paras/opt/anaconda3/lib/python3.8/site-packages/lightkurve/utils.py", line 555, in wrapper
    return f(*args, **kwargs)

  File "/Users/paras/opt/anaconda3/lib/python3.8/site-packages/lightkurve/search.py", line 355, in download
    return self._download_one(

  File "/Users/paras/opt/anaconda3/lib/python3.8/site-packages/lightkurve/search.py", line 248, in _download_one
    raise SearchError(

SearchError: Unable to download FFI cutout. Desired target coordinates may be too near the edge of the FFI.Error: 502 Server Error: Bad Gateway for url: https://mast.stsci.edu/tesscut/api/v0.1/sector
```

**Comment by barentsen** [comment]
@akankshaprl I'm afraid authenticated proxies are not currently supported by either `lightkurve` or `astroquery` right now.

My best advice for now would be to use Lightkurve from a service that offers running a Python terminal or notebook in the cloud (e.g., Google Colab, AWS).
