### ISSUE TITLE
Normalize and outlier removal functions not working with default TESS light curves

### ISSUE THREAD

**Issue by mschwamb** [lightkurve/lightkurve#1268]
#### Problem description
normalize and removing outliers not working with TESS light curves 

#### Example

import lightkurve as lk
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import astropy.units as u
%matplotlib notebook 

star_name='TIC 140830390'
sector=39
search_result= lk.search_lightcurve(star_name, mission='TESS', sector=sector, exptime=120, author='SPOC')#print(len(search_result))
lc=search_result.download()
lc.plot()

lc = lc.normalize()
lc= lc.remove_outliers(sigma=6) # clip the light curve to remove deviant datapoints greater than 6 sigma

import platform; print(platform.platform())
import sys; print("Python", sys.version)
import lightkurve as lk; print("lightkurve", lk.__version__)
import astropy; print("astropy", astropy.__version__)
import numpy as np; print("numpy", np.__version__)

macOS-10.16-x86_64-i386-64bit
Python 3.9.15 (main, Nov 24 2022, 08:29:02) 
[Clang 14.0.6 ]
lightkurve 2.3.0
astropy 5.2
numpy 1.24.1

#### Expected behavior

This used to give me a normalized light curve with the outlier removed. Now I am getting these errors

TypeError                                 Traceback (most recent call last)
Cell In[3], line 1
----> 1 lc = lc.normalize()
      2 lc= lc.remove_outliers(sigma=6)

File ~/opt/anaconda3/envs/lightkurve/lib/python3.9/site-packages/lightkurve/lightcurve.py:1119, in LightCurve.normalize(self, unit)
   1083 """Returns a normalized version of the light curve.
   1084 
   1085 The normalized light curve is obtained by dividing the ``flux`` and
   (...)
   1116     from zero.
   1117 """
   1118 validate_method(unit, ["unscaled", "percent", "ppt", "ppm"])
-> 1119 median_flux = np.nanmedian(self.flux)
   1120 std_flux = np.nanstd(self.flux)
   1122 # If the median flux is within half a standard deviation from zero, the
   1123 # light curve is likely zero-centered and normalization makes no sense.

File <__array_function__ internals>:200, in nanmedian(*args, **kwargs)

File ~/opt/anaconda3/envs/lightkurve/lib/python3.9/site-packages/astropy/units/quantity.py:1818, in Quantity.__array_function__(self, function, types, args, kwargs)
   1805 # A function should be in one of the following sets or dicts:
   1806 # 1. SUBCLASS_SAFE_FUNCTIONS (set), if the numpy implementation
   1807 #    supports Quantity; we pass on to ndarray.__array_function__.
   (...)
   1815 # function is in none of the above, we simply call the numpy
   1816 # implementation.
   1817 if function in SUBCLASS_SAFE_FUNCTIONS:
-> 1818     return super().__array_function__(function, types, args, kwargs)
   1820 elif function in FUNCTION_HELPERS:
   1821     function_helper = FUNCTION_HELPERS[function]

File ~/opt/anaconda3/envs/lightkurve/lib/python3.9/site-packages/astropy/utils/masked/core.py:864, in MaskedNDArray.__array_function__(self, function, types, args, kwargs)
    862 dispatched_function = DISPATCHED_FUNCTIONS[function]
    863 try:
--> 864     dispatched_result = dispatched_function(*args, **kwargs)
    865 except NotImplementedError:
    866     return self._not_implemented_or_raise(function, types)

File ~/opt/anaconda3/envs/lightkurve/lib/python3.9/site-packages/astropy/utils/masked/function_helpers.py:1044, in masked_nanfunc.<locals>.nanfunc(a, *args, **kwargs)
   1041     if fill_value is not None:
   1042         a = a.filled(fill_value)
-> 1044 return np_func(a, *args, **kwargs)

File <__array_function__ internals>:200, in median(*args, **kwargs)

File ~/opt/anaconda3/envs/lightkurve/lib/python3.9/site-packages/astropy/units/quantity.py:1818, in Quantity.__array_function__(self, function, types, args, kwargs)
   1805 # A function should be in one of the following sets or dicts:
   1806 # 1. SUBCLASS_SAFE_FUNCTIONS (set), if the numpy implementation
   1807 #    supports Quantity; we pass on to ndarray.__array_function__.
   (...)
   1815 # function is in none of the above, we simply call the numpy
   1816 # implementation.
   1817 if function in SUBCLASS_SAFE_FUNCTIONS:
-> 1818     return super().__array_function__(function, types, args, kwargs)
   1820 elif function in FUNCTION_HELPERS:
   1821     function_helper = FUNCTION_HELPERS[function]

File ~/opt/anaconda3/envs/lightkurve/lib/python3.9/site-packages/astropy/utils/masked/core.py:864, in MaskedNDArray.__array_function__(self, function, types, args, kwargs)
    862 dispatched_function = DISPATCHED_FUNCTIONS[function]
    863 try:
--> 864     dispatched_result = dispatched_function(*args, **kwargs)
    865 except NotImplementedError:
    866     return self._not_implemented_or_raise(function, types)

File ~/opt/anaconda3/envs/lightkurve/lib/python3.9/site-packages/astropy/utils/masked/function_helpers.py:592, in median(a, axis, out, **kwargs)
    590 if NUMPY_LT_1_25:
    591     keepdims = kwargs.pop("keepdims", False)
--> 592     r, k = np.lib.function_base._ureduce(
    593         a, func=_masked_median, axis=axis, out=out, **kwargs
    594     )
    595     return (r.reshape(k) if keepdims else r) if out is None else out
    597 else:

File ~/opt/anaconda3/envs/lightkurve/lib/python3.9/site-packages/astropy/units/quantity.py:1255, in Quantity.__iter__(self)
   1253 def __iter__(self):
   1254     if self.isscalar:
-> 1255         raise TypeError(
   1256             f"'{self.__class__.__name__}' object with a scalar value is not"
   1257             " iterable"
   1258         )
   1260     # Otherwise return a generator
   1261     def quantity_iter():

TypeError: 'MaskedQuantity' object with a scalar value is not iterable

#### Environment

-  platform (e.g. Linux, OSX, Windows):
-  lightkurve version (e.g. 1.0b6):
-  installation method (e.g. pip, conda, source):

installed via conda (also same behavior when I installed in a separate conda environment with pip)

macOS-10.16-x86_64-i386-64bit
Python 3.9.15 (main, Nov 24 2022, 08:29:02) 
[Clang 14.0.6 ]
lightkurve 2.3.0
astropy 5.2
numpy 1.24.1

**Comment by warrickball** [comment]
I'm pretty sure I've just hit exactly the same issue, though in my case indirectly via `stitch()`. Here's a script that reproduces the error:
```python
import lightkurve as lk

lcs = lk.search_lightcurve('HD 45364', mission='TESS', exptime=120, author='SPOC').download_all()
lc = lcs[0].normalize()
```
For me, this produces
```
  File "/home/wball/try/lightkurve/stitch-bug.py", line 4, in <module>
    lc = lcs[0].normalize()
         ^^^^^^^^^^^^^^^^^^
  File "/home/wball/.local/lib/python3.11/site-packages/lightkurve/lightcurve.py", line 1119, in normalize
    median_flux = np.nanmedian(self.flux)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "<__array_function__ internals>", line 200, in nanmedian
  File "/home/wball/.local/lib/python3.11/site-packages/astropy/units/quantity.py", line 1818, in __array_function__
    return super().__array_function__(function, types, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wball/.local/lib/python3.11/site-packages/astropy/utils/masked/core.py", line 864, in __array_function__
    dispatched_result = dispatched_function(*args, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wball/.local/lib/python3.11/site-packages/astropy/utils/masked/function_helpers.py", line 1044, in nanfunc
    return np_func(a, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<__array_function__ internals>", line 200, in median
  File "/home/wball/.local/lib/python3.11/site-packages/astropy/units/quantity.py", line 1818, in __array_function__
    return super().__array_function__(function, types, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wball/.local/lib/python3.11/site-packages/astropy/utils/masked/core.py", line 864, in __array_function__
    dispatched_result = dispatched_function(*args, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wball/.local/lib/python3.11/site-packages/astropy/utils/masked/function_helpers.py", line 592, in median
    r, k = np.lib.function_base._ureduce(
    ^^^^
  File "/home/wball/.local/lib/python3.11/site-packages/astropy/units/quantity.py", line 1255, in __iter__
    raise TypeError(
TypeError: 'MaskedQuantity' object with a scalar value is not iterable
```
I'm using
- Fedora 37
- Python 3.11.1
- NumPy 1.24.1
- Lightkurve 2.3.0
- Astropy 5.2

**Comment by warrickball** [comment]
@mschwamb, can you try updating to Astropy 5.2.1, which was released about a week ago? That fixed the issue for me.

For full context, I had a look in Astropy and found [this Astropy bug](https://github.com/astropy/astropy/issues/14236), which reports the core issue: if I try `np.nanmedian(lcs[0].flux)` I get the same error. That also links to [this issue](https://github.com/astropy/astropy/issues/14189) about NumPy 1.24 breaking Astropy 5.2, which was fixed by [this pull request](https://github.com/astropy/astropy/pull/14193) about a month ago. Those changes are [in Astropy 5.2.1](https://docs.astropy.org/en/stable/changelog.html#other-changes-and-additions).

**Comment by mschwamb** [comment]
Yep that fixed it. Moving 5.2.1 sorted it.

**Comment by mschwamb** [comment]
Thanks @warrickball !
