### ISSUE TITLE
Error when using lc.remove_row

### ISSUE THREAD

**Issue by jcsmithhere** [lightkurve/lightkurve#836]
#### Problem description
An error is occurring when using `lc[x:y]` in combination with `lc.remove_row()`. The error only occurs in certain situations. The error might be in astropy or it might be our usage of the astropy.timeseries class.

#### Example

The error appears to only occur after first using the `lc[x:y]` syntax where x > 0. 

```python
lc = search_lightcurve('TIC 99180739', mission='tess', sector=10).download(flux_column='sap_flux')
lc_short = lc[10:1000]
lc_short.remove_row(10)
lc_short.remove_row(10)
```

The second call to `remove_row` results in an error: 

```python
Traceback (most recent call last):
  File "/Users/bohr/opt/anaconda3/envs/lightkurve-env/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-362ca01ec676>", line 1, in <module>
    lc_short.remove_row(1)
  File "/Users/bohr/opt/anaconda3/envs/lightkurve-env/lib/python3.8/site-packages/astropy/table/table.py", line 2227, in remove_row
    self.remove_rows(index)
  File "/Users/bohr/opt/anaconda3/envs/lightkurve-env/lib/python3.8/site-packages/astropy/table/table.py", line 2275, in remove_rows
    index.remove_rows(row_specifier)
  File "/Users/bohr/opt/anaconda3/envs/lightkurve-env/lib/python3.8/site-packages/astropy/table/index.py", line 554, in remove_rows
    self.copy().remove_rows(row_specifier)
  File "/Users/bohr/opt/anaconda3/envs/lightkurve-env/lib/python3.8/site-packages/astropy/table/index.py", line 228, in remove_rows
    self.remove_row(row, reorder=False)
  File "/Users/bohr/opt/anaconda3/envs/lightkurve-env/lib/python3.8/site-packages/astropy/table/index.py", line 248, in remove_row
    raise ValueError(f"Could not remove row {row} from index")
ValueError: Could not remove row 1 from index
```

#### Environment

-  platform: Linux 
-  lightkurve version: master branch
-  installation method: source
- astropy version: 4.1rc1

**Comment by barentsen** [comment]
Thanks @jcsmithhere!

@dhomeier Would you be interested in having a look to diagnoise if this problem is specific to Table, TimeSeries, or LightCurve?

**Comment by dhomeier** [comment]
Thanks, it can be isolated to `TimeSeries`, so I've reported it upstream.

**Comment by barentsen** [comment]
@dhomeier Thanks so much!! :+1:

**Comment by barentsen** [comment]
I am closing this issue because the origin of the bug lies within AstroPy.  See the AstroPy issue opened by Derek above for more information.

Thanks Jeff & Derek!
