### ISSUE TITLE
No attribute centroid_col when writing QLP lightcurve to FITS

### ISSUE THREAD

**Issue by warrickball** [lightkurve/lightkurve#957]
Please don't hate me.

#### Problem description

I'm getting the error `AttributeError: object has no attribute centroid_col` when trying to write a QLP lightcurve to FITS.
```$ python3 mwe.py 
/home/wball/.local/lib/python3.9/site-packages/lightkurve/lightcurve.py:965: LightkurveWarning: The light curve already appears to be in relative units; `normalize()` will convert the light curve into relative units for a second time, which is probably not what you want.
  warnings.warn(
Traceback (most recent call last):
  File "/home/wball/work/steve/mwe.py", line 6, in <module>
    lc.to_fits('hv2112.fits')
  File "/home/wball/.local/lib/python3.9/site-packages/lightkurve/lightcurve.py", line 2912, in to_fits
    "MOM_CENTR1": self.centroid_col,
  File "/home/wball/.local/lib/python3.9/site-packages/lightkurve/lightcurve.py", line 331, in __getattr__
    raise AttributeError(f"object has no attribute {name}")
AttributeError: object has no attribute centroid_col
```
I guess the FITS writer presumes `MOM_CENTR1` is present but it isn't in QLP (and perhaps other?) HLSPs. I'll have a closer look at lightkurve's source if I get some time later and no-one on the team gets there first. I feel like I raise a lot issues so I'd feel a bit better if I could close one too!

#### Example

```python
import lightkurve as lk

s = lk.search_lightcurve('HV 2112', mission='TESS', author='QLP', exptime=1800)
lcs = s.download_all()
lc = lcs.stitch()
lc.to_fits('hv2112.fits')
```

#### Expected behavior
The FITS file would be written out successfully.

#### Environment

- Fedora 33
- Python 3.9.1
- lightkurve 2.0.0, via pip

**Comment by barentsen** [comment]
Thanks for opening this issue @warrickball!  Opening issues is the first step towards getting all the kinks ironed out of Lightkurve v2. I appreciate it!

This looks like a real bug indeed.

I will not be able to debug this right away, so feel free to have a look at the code if you want!  I recently updated the documentation on how to make changes to the code here:

    https://docs.lightkurve.org/about/contributing.html

I will comment below should I start working on this.

**Comment by barentsen** [comment]
Side note: because `LightCurve` objects are now AstroPy tables, they can now be saved in FITS and other formats as follows:

```python
lc.write("filename.fits")
```

This works in the example posted above, however the FITS file produced in this way does not fully adopt the typical TESS light curve file format, and there appears to be a bug in the way the time values are stored in this way.

We'll eventually want to add dedicated writer function in `lightkurve.io` so that one can use e.g. `lc.write("filename.fits", format="tess")`.

**Comment by rebekah9969** [comment]
An easy work around might be to do something like, 
lc.meta['MOM_CENTR1'] = np.nan 
lc.meta['MOM_CENTR2'] = np.nan
lc.centroid_col = 'nan'
lc.centroid_row = 'nan'
lc.to_fits('hv2112.fits')

or to follow the method outlined here https://docs.lightkurve.org/tutorials/2-creating-light-curves/2-1-saving-a-light-curve.html

**Comment by orionlee** [comment]
The issue is essentially a symptom of the underlying problem, discussed in https://github.com/lightkurve/lightkurve/issues/896
